import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Home from '@/components/Home'
import Test from '@/components/Test'
import Spaces from '@/components/Spaces'
/* import Projects from '@/components/Projects' */

const inter = Inter({ subsets: ['latin'] })

export default function Page() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Home/>
      <Spaces/>
      <Test/>
      <Spaces/>
      {/* <Projects/> */}
    </>
  )
}
